dist: trusty
language: python
jobs:
  include:
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install html2text
- python3 -m pip install pydiatra $pyflakes
- python3 -m pip install restructuredtext-lint pygments
script:
- ./hackerlates --help
- ./hackerlates --limit 3 jwilk
- python3 -m pydiatra .
- python3 -m pyflakes .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
